services:

  # ─── POSTGRESQL DATABASE ─────────────────────────────────
  db:
    image: postgres:18-alpine
    container_name: tmdt_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tmdt_db
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - tmdt_network

  # ─── NESTJS APP ──────────────────────────────────────────
  app:
    build:
      context: .          
      dockerfile: Dockerfile

    container_name: tmdt_app
    restart: always

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/tmdt_db

      JWT_SECRET: secret
      JWT_EXPIRES_IN: 1d
      PORT: 3000
      FRONTEND_URL: http://localhost:5173
      ADMIN_PASSWORD: 123456

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}

      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      FACEBOOK_CALLBACK_URL: ${FACEBOOK_CALLBACK_URL}

      VNPAY_TMN_CODE: ${VNPAY_TMN_CODE}
      VNPAY_HASH_SECRET: ${VNPAY_HASH_SECRET}
      VNPAY_PAYMENT_URL: ${VNPAY_PAYMENT_URL}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL}

      RESEND_API_KEY: ${RESEND_API_KEY}
      RESET_TOKEN_TTL_MINUTES: $RESET_TOKEN_TTL_MINUTES
      FRONTEND_FORGOT_PASSWORD_URL: ${FRONTEND_FORGOT_PASSWORD_URL}

    ports:
      - "3000:3000"

    networks:
      - tmdt_network

volumes:
  postgres_data:
    name: tmdt_postgres_data

networks:
  tmdt_network:
    driver: bridge