server {
    listen 80;
    server_name _;

    # =========================
    # FRONTEND
    # =========================
    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
    }

    # =========================
    # BACKEND API
    # =========================
    location /api/ {
        client_max_body_size 100M;
        proxy_pass http://backend:3000;

        # BẮT BUỘC
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header Cookie $http_cookie;
        proxy_set_header Authorization $http_authorization;
    }

    # =========================
    # STATIC UPLOADS (banner, product images)
    # Nest serve-static: /uploads -> backend/uploads/
    # =========================
    location /uploads/ {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}